name: 'Monorepo Split'

on:
  push:
    branches:
      - main

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: "ramsey/composer-install@v1"
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@2.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'spatie'
          split-repository-name: '${{ matrix.package }}'
          user-name: "riasvdv"
          user-email: "rias@spatie.be"
